import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { after, before, test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const supporter = "00000000-0000-4000-8000-000000000001";
const creator = "00000000-0000-4000-8000-000000000002";
const other = "00000000-0000-4000-8000-000000000003";
const migrations = [
  "20260920_wallet_ledger.sql",
  "20260921_wallet_safety.sql",
  "20260922_wallet_capability_recovery.sql",
  "20260923_wallet_balance_recovery.sql",
  "20260923_wallet_table_privileges.sql",
];

async function baseDatabase(legacyLike = "self") {
  const database = new PGlite();
  await database.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    grant usage on schema public, auth to authenticated, anon, service_role;
    create table public.ads(
      id bigint primary key,
      user_id uuid references auth.users,
      support_total numeric default 0,
      moderation_status text default 'approved',
      promotion_stopped_at timestamptz,
      promotion_allocation jsonb default '{}'
    );
    create table public.supports(
      id bigint generated by default as identity primary key,
      user_id uuid,
      ad_id bigint references public.ads,
      amount numeric check(amount >= 0.50),
      stripe_session_id text unique,
      stripe_payment_intent_id text unique
    );
    create table public.creator_accounts(
      user_id uuid primary key,
      stripe_account_id text,
      onboarding_complete boolean,
      charges_enabled boolean,
      payouts_enabled boolean
    );
    create table public.likes(
      id bigint generated by default as identity primary key,
      user_id uuid references auth.users,
      ad_id bigint references public.ads on delete cascade,
      created_at timestamptz default now(),
      unique(user_id, ad_id)
    );
    alter table public.likes enable row level security;
    create policy "Anyone can view likes" on public.likes for select using (true);
    create policy "Users can like ads they do not own" on public.likes for insert
      to authenticated with check (auth.uid() = user_id);
    create policy "Users can remove their own likes" on public.likes for delete
      to authenticated using (auth.uid() = user_id);
    grant all on public.likes to anon, authenticated, service_role;
    grant all on sequence public.likes_id_seq to anon, authenticated, service_role;
    insert into auth.users values ('${supporter}'), ('${creator}'), ('${other}');
    insert into public.ads(id,user_id) values
      (1,'${creator}'), (2,'${creator}'), (3,'${creator}'),
      (4,'${supporter}'), (5,'${creator}'), (6,'${creator}'),
      (7,'${creator}');
    insert into public.creator_accounts values
      ('${creator}','acct_creator',true,true,true);
  `);
  if (legacyLike === "self") {
    await database.query("insert into likes(user_id,ad_id) values ($1,4)", [supporter]);
  } else if (legacyLike === "valid") {
    await database.query("insert into likes(user_id,ad_id) values ($1,1)", [supporter]);
  }
  for (const file of migrations) {
    let sql = readFileSync(new URL(`../supabase/migrations/${file}`, import.meta.url), "utf8");
    sql = sql.replace("create extension if not exists pgcrypto;", "");
    await database.exec(sql);
  }
  return database;
}

const scalar = async (database, sql, args = []) =>
  (await database.query(sql, args)).rows[0];

let db;
before(async () => {
  db = await baseDatabase();
  const paidSeed = readFileSync(
    new URL("../supabase/migrations/20260923093000_paid_seeds.sql", import.meta.url),
    "utf8",
  );
  await db.exec(paidSeed);
});
after(() => db.close());

test("first Seed atomically records one cent and every replay remains once-only", async () => {
  await db.query("select record_wallet_topup($1,$2,$3,1000)", ["cs_seed", "pi_seed", supporter]);
  const request = "10000000-0000-4000-8000-000000000001";
  const first = (await scalar(db,
    "select seed_ad_from_wallet($1,1,$2) as result", [supporter, request])).result;
  const replay = (await scalar(db,
    "select seed_ad_from_wallet($1,1,$2) as result", [supporter, request])).result;
  const otherRequest = (await scalar(db,
    "select seed_ad_from_wallet($1,1,$2) as result",
    [supporter, "10000000-0000-4000-8000-000000000002"])).result;

  assert.equal(first.recorded, true);
  assert.equal(first.seeded, true);
  assert.equal(first.already_seeded, false);
  assert.equal(replay.already_seeded, true);
  assert.equal(otherRequest.already_seeded, true);
  assert.equal((await scalar(db,
    "select available_cents from wallets where user_id=$1", [supporter])).available_cents, 999);
  assert.deepEqual(await scalar(db, `select
    (select count(*)::int from ad_seeds) as seeds,
    (select count(*)::int from supports) as supports,
    (select count(*)::int from wallet_transactions where entry_type='support_debit') as debits,
    (select count(*)::int from likes) as archived_likes,
    (select round(support_total*100)::int from ads where id=1) as support_cents`),
  { seeds: 1, supports: 1, debits: 1, archived_likes: 1, support_cents: 1 });
  const split = await scalar(db,
    "select creator_amount_micros,platform_amount_micros,source from supports where id=$1",
    [first.support_id]);
  assert.equal(split.creator_amount_micros, 9000);
  assert.equal(split.platform_amount_micros, 1000);
  assert.equal(split.source, "wallet_seed");
  const metadata = (await scalar(db,
    "select metadata from wallet_transactions where request_id=$1", [request])).metadata;
  assert.equal(metadata.purpose, "seed");
});

test("Support and Seed request identities cannot be reused across actions", async () => {
  const supportRequest = "20000000-0000-4000-8000-000000000001";
  await db.query("select support_ad_from_wallet($1,2,1,$2)", [supporter, supportRequest]);
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,1,$2)", [supporter, supportRequest]),
    /REQUEST_ID_CONFLICT/,
  );
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,2,$2)", [supporter, supportRequest]),
    /REQUEST_ID_CONFLICT/,
  );
  assert.equal((await scalar(db, "select count(*)::int as n from ad_seeds where ad_id=2")).n, 0);

  const seedRequest = "20000000-0000-4000-8000-000000000002";
  await db.query("select seed_ad_from_wallet($1,3,$2)", [supporter, seedRequest]);
  await assert.rejects(
    db.query("select support_ad_from_wallet($1,3,1,$2)", [supporter, seedRequest]),
    /REQUEST_ID_CONFLICT/,
  );
  assert.equal((await scalar(db,
    "select count(*)::int as n from wallet_transactions where request_id=$1", [seedRequest])).n, 1);
});

test("Seed rejects every ineligible wallet/ad path and marker failure without partial money writes", async () => {
  const before = await scalar(db, `select
    (select available_cents from wallets where user_id='${supporter}') as balance,
    (select count(*)::int from supports) as supports,
    (select count(*)::int from ad_seeds) as seeds`);

  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,4,gen_random_uuid())", [supporter]),
    /SEED_OWN_AD/,
  );
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,2,gen_random_uuid())", [other]),
    /WALLET_NOT_FUNDED/,
  );
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,999,gen_random_uuid())", [supporter]),
    /AD_NOT_FOUND/,
  );
  await db.exec("update ads set moderation_status='pending_scan' where id=5");
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,5,gen_random_uuid())", [supporter]),
    /AD_NOT_APPROVED/,
  );
  await db.exec("update ads set promotion_stopped_at=now() where id=7");
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,7,gen_random_uuid())", [supporter]),
    /AD_NOT_APPROVED/,
  );
  await db.exec("update ads set promotion_stopped_at=null where id=7");

  await db.query("update wallets set available_cents=0 where user_id=$1", [supporter]);
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,7,gen_random_uuid())", [supporter]),
    /INSUFFICIENT_WALLET_BALANCE/,
  );
  await db.query("update wallets set available_cents=$2 where user_id=$1", [supporter, before.balance]);

  await db.exec(`
    create function fail_test_seed_marker() returns trigger language plpgsql as $$
    begin
      if new.ad_id=6 then raise exception 'TEST_MARKER_FAILURE'; end if;
      return new;
    end $$;
    create trigger fail_test_seed_marker before insert on ad_seeds
      for each row execute function fail_test_seed_marker();
  `);
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,6,gen_random_uuid())", [supporter]),
    /TEST_MARKER_FAILURE/,
  );

  await db.query("update wallets set status='frozen' where user_id=$1", [supporter]);
  await assert.rejects(
    db.query("select seed_ad_from_wallet($1,7,gen_random_uuid())", [supporter]),
    /WALLET_FROZEN/,
  );
  await db.query("update wallets set status='active' where user_id=$1", [supporter]);

  assert.deepEqual(await scalar(db, `select
    (select available_cents from wallets where user_id='${supporter}') as balance,
    (select count(*)::int from supports) as supports,
    (select count(*)::int from ad_seeds) as seeds`), before);
});

test("two users may Seed the same ad while narrow getters reveal only their own state", async () => {
  await db.query("select record_wallet_topup($1,$2,$3,1000)", ["cs_other", "pi_other", other]);
  await db.query("select seed_ad_from_wallet($1,1,gen_random_uuid())", [other]);
  const counts = await db.query("select * from get_seed_counts() where ad_id=1");
  assert.equal(Number(counts.rows[0].seed_count), 2);

  await db.query("select set_config('request.jwt.claim.sub',$1,false)", [other]);
  await db.exec("set role authenticated");
  try {
    const mine = await db.query("select * from get_my_seeded_ad_ids()");
    assert.deepEqual(mine.rows.map(row => Number(row.ad_id)), [1]);
    await assert.rejects(
      db.query("insert into ad_seeds(user_id,ad_id,support_id,wallet_request_id) values ($1,2,1,gen_random_uuid())", [other]),
      /permission denied/,
    );
    await assert.rejects(
      db.query("delete from ad_seeds where user_id=$1", [other]),
      /permission denied/,
    );
    await assert.rejects(
      db.query("select * from ad_seeds"),
      /permission denied/,
    );
    await assert.rejects(
      db.query("select seed_ad_from_wallet($1,2,gen_random_uuid())", [other]),
      /permission denied/,
    );
    await assert.rejects(
      db.query("insert into likes(user_id,ad_id) values ($1,2)", [other]),
      /permission denied/,
    );
  } finally {
    await db.exec("reset role");
  }

  await db.exec("set role service_role");
  try {
    await assert.rejects(
      db.query("delete from ad_seeds"),
      /permission denied/,
    );
  } finally {
    await db.exec("reset role");
  }
});

test("migration refuses to discard a legitimate legacy Like", async () => {
  const reviewDb = await baseDatabase("valid");
  try {
    const paidSeed = readFileSync(
      new URL("../supabase/migrations/20260923093000_paid_seeds.sql", import.meta.url),
      "utf8",
    );
    await assert.rejects(reviewDb.exec(paidSeed), /LEGACY_LIKES_REQUIRE_REVIEW/);
    await reviewDb.exec("rollback");
    assert.equal((await scalar(reviewDb,
      "select to_regclass('public.ad_seeds') is null as absent")).absent, true);
  } finally {
    await reviewDb.close();
  }
});
