import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { before, after, test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
const supporter = '00000000-0000-4000-8000-000000000001';
const creator = '00000000-0000-4000-8000-000000000002';
const other = '00000000-0000-4000-8000-000000000003';
const refundUser = '00000000-0000-4000-8000-000000000004';
const scalar = async (sql, args = []) => (await db.query(sql, args)).rows[0];
before(async () => {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    grant usage on schema public, auth to authenticated, anon, service_role;
    create table public.ads(id bigint primary key, user_id uuid references auth.users,
      support_total numeric default 0, moderation_status text default 'approved',
      promotion_stopped_at timestamptz, promotion_allocation jsonb default '{}');
    create table public.supports(id bigint generated by default as identity primary key,
      user_id uuid, ad_id bigint references public.ads, amount numeric check(amount >= 0.50),
      stripe_session_id text unique, stripe_payment_intent_id text unique);
    create table public.creator_accounts(user_id uuid primary key,
      stripe_account_id text, onboarding_complete boolean, charges_enabled boolean, payouts_enabled boolean);
    insert into auth.users values ('${supporter}'),('${creator}'),('${other}'),('${refundUser}');
    insert into public.ads(id,user_id) values (1,'${creator}');
    insert into public.creator_accounts values ('${creator}','acct_original',true,true,true);
  `);
  for (const file of ['20260920_wallet_ledger.sql', '20260921_wallet_safety.sql', '20260922_wallet_capability_recovery.sql', '20260923_wallet_balance_recovery.sql', '20260923_wallet_table_privileges.sql']) {
    let sql = readFileSync(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8');
    // PGlite has builtin gen_random_uuid; it does not ship the pgcrypto extension.
    sql = sql.replace('create extension if not exists pgcrypto;', '');
    await db.exec(sql);
  }
});
after(() => db.close());

test('actual RPC credits once and one-cent Support preserves exact shares', async () => {
  await db.query('select record_wallet_topup($1,$2,$3,1000)', ['cs_1','pi_1',supporter]);
  await db.query('select record_wallet_topup($1,$2,$3,1000)', ['cs_1','pi_1',supporter]);
  const request = '10000000-0000-4000-8000-000000000001';
  await db.query('select spend_wallet_support($1,1,1,$2)', [supporter,request]);
  await db.query('select spend_wallet_support($1,1,1,$2)', [supporter,request]);
  assert.equal((await scalar('select available_cents from wallets where user_id=$1',[supporter])).available_cents,999);
  const row = await scalar('select creator_amount_micros,platform_amount_micros from supports');
  assert.equal(row.creator_amount_micros,9000);
  assert.equal(row.platform_amount_micros,1000);
  await assert.rejects(db.query('select spend_wallet_support($1,1,2,$2)',[supporter,request]), /REQUEST_ID_CONFLICT/);
  await assert.rejects(db.query('select spend_wallet_support($1,1,1000,gen_random_uuid())',[supporter]), /INSUFFICIENT/);
});

let settlementId;
let inFlightSettlementId;
test('actual settlement claim and guard preserve destination and retry deadline', async () => {
  await db.query('select spend_wallet_support($1,1,999,gen_random_uuid())',[supporter]);
  const claimed = (await db.query('select * from claim_due_wallet_settlements(25)')).rows;
  assert.equal(claimed.length,1);
  assert.equal(claimed[0].creator_transfer_cents,900);
  settlementId = claimed[0].settlement_id;
  const first = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(first.allowed,true);
  await db.exec("update creator_accounts set stripe_account_id='acct_changed'");
  const second = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(second.destination,'acct_original');
  assert.equal(second.retry_before,first.retry_before);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
});

test('capability recovery records one key without changing identity, destination, time or accounting', async () => {
  await db.query('select retry_wallet_settlement($1,$2)', [settlementId,'capability failure']);
  const beforeGuard = await scalar('select * from wallet_transfer_guards where settlement_id=$1',[settlementId]);
  const beforeState = await scalar('select * from ad_settlement_state where ad_id=1');
  const beforeSettlement = await scalar('select * from support_settlements where id=$1',[settlementId]);
  const key = `adbattle-settlement-${settlementId}`;
  const args = [settlementId,key,'req_verified','insufficient_capabilities_for_transfer'];
  for (const bad of [
    [settlementId,key,'req_verified','api_error'],
    [settlementId,key+'-other','req_verified',args[3]],
    [settlementId,key,null,args[3]],
  ]) await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',bad),/INVALID_CAPABILITY/);
  // The preceding test changed the current account, not the frozen destination.
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',args),/RECOVERY_DESTINATION_MISMATCH/);
  assert.deepEqual(await scalar('select * from wallet_transfer_guards where settlement_id=$1',[settlementId]),beforeGuard);
  await db.exec("update creator_accounts set stripe_account_id='acct_original'");
  await db.query('update wallet_transfer_guards set manual_review=true where settlement_id=$1',[settlementId]);
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',args),/RECOVERY_BLOCKED/);
  await db.query('update wallet_transfer_guards set manual_review=false where settlement_id=$1',[settlementId]);
  await db.exec('update creator_accounts set payouts_enabled=false');
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',args),/RECOVERY_CREATOR_NOT_READY/);
  await db.exec('update creator_accounts set payouts_enabled=true');
  const first = (await scalar('select authorize_wallet_capability_recovery($1,$2,$3,$4) as result',args)).result;
  const repeat = (await scalar('select authorize_wallet_capability_recovery($1,$2,$3,$4) as result',args)).result;
  assert.equal(first.created,true);
  assert.equal(repeat.created,false);
  assert.equal(repeat.idempotency_key,first.idempotency_key);
  assert.notEqual(first.idempotency_key,key);
  const guard = (await scalar('select prepare_wallet_transfer($1) as g',[settlementId])).g;
  assert.equal(guard.idempotency_key,first.idempotency_key);
  assert.equal(guard.destination,beforeGuard.destination);
  assert.deepEqual(await scalar('select * from ad_settlement_state where ad_id=1'),beforeState);
  assert.deepEqual(await scalar('select * from support_settlements where id=$1',[settlementId]),beforeSettlement);
  const after = await scalar('select * from wallet_transfer_guards where settlement_id=$1',[settlementId]);
  assert.deepEqual(after.first_attempt_at,beforeGuard.first_attempt_at);
  assert.equal(after.manual_review,false);
  assert.equal(after.capability_recovery_request_id,'req_verified');
  await db.exec("update creator_accounts set stripe_account_id='acct_changed'");
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',args),/RECOVERY_DESTINATION_MISMATCH/);
  await db.exec("update creator_accounts set stripe_account_id='acct_original'");
  await db.exec('set role authenticated');
  try {
    await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',args),/permission denied/);
    await assert.rejects(db.query('select prepare_wallet_transfer_before_recovery($1)',[settlementId]),/permission denied/);
  } finally { await db.exec('reset role'); }
});

test('balance recovery independently enforces predecessor, funds, roles and every existing guard', async () => {
  const key=`adbattle-settlement-${settlementId}-capability-recovery-1`;
  const args=[settlementId,key,'req_balanceRejected','balance_insufficient',1912,'req_balanceSnapshot'];
  const rpc='select authorize_wallet_balance_recovery($1,$2,$3,$4,$5,$6) as result';
  const before=await scalar('select * from wallet_transfer_guards where settlement_id=$1',[settlementId]);
  const beforeState=await scalar('select * from ad_settlement_state where ad_id=1');
  const beforeSettlement=await scalar('select * from support_settlements where id=$1',[settlementId]);
  for(const patch of [
    {1:`adbattle-settlement-${settlementId}`},{1:key+'-other'},{2:null},
    {3:'api_error'},{4:null},{4:899},{5:null},{5:'req_balanceRejected'},
  ]) {
    const bad=[...args]; for(const [index,value] of Object.entries(patch)) bad[index]=value;
    await assert.rejects(db.query(rpc,bad),/INVALID_BALANCE|BALANCE_TOO_LOW/);
  }
  for(const mutate of [
    "update wallet_transfer_guards set manual_review=true",
    "update wallet_transfer_guards set first_attempt_at=now()-interval '21 hours'",
    "update wallet_transfer_guards set first_attempt_at=null",
    "update wallet_transfer_guards set capability_recovery_key=null, capability_recovery_request_id=null, capability_recovered_at=null",
    "update creator_accounts set payouts_enabled=false",
    "update creator_accounts set stripe_account_id='acct_other'",
    "update ad_settlement_state set active_settlement_id=null",
    "update support_settlements set status='succeeded'",
    `select record_wallet_payment_risk('pi_1','${supporter}',0,true,'evt_guard','charge.dispute.created')`,
  ]) {
    await db.exec('begin');
    try {
      await db.exec(mutate);
      await assert.rejects(db.query(rpc,args),/RECOVERY_/);
    } finally { await db.exec('rollback'); }
  }
  for(const role of ['anon','authenticated']) {
    await db.exec('set role '+role);
    try { await assert.rejects(db.query(rpc,args),/permission denied/); }
    finally { await db.exec('reset role'); }
  }
  await db.exec('set role service_role');
  try {
    await assert.rejects(db.query('select prepare_wallet_transfer_before_balance_recovery($1)',[settlementId]),/permission denied/);
    const first=(await scalar(rpc,args)).result;
    const repeat=(await scalar(rpc,args)).result;
    assert.equal(first.created,true); assert.equal(repeat.created,false);
    assert.equal(first.idempotency_key,`adbattle-settlement-${settlementId}-balance-recovery-1`);
    assert.equal(repeat.idempotency_key,first.idempotency_key);
    const ready=(await scalar('select prepare_wallet_transfer($1) as result',[settlementId])).result;
    assert.equal(ready.idempotency_key,first.idempotency_key);
    assert.equal(ready.balance_recovery_supported,true);
  } finally { await db.exec('reset role'); }
  const after=await scalar('select * from wallet_transfer_guards where settlement_id=$1',[settlementId]);
  for(const name of Object.keys(before).filter(k=>!k.startsWith('balance_'))) assert.deepEqual(after[name],before[name]);
  assert.equal(after.balance_recovery_request_id,'req_balanceRejected');
  assert.equal(after.balance_recovery_balance_request_id,'req_balanceSnapshot');
  assert.equal(after.balance_recovery_available_cents,1912);
  assert.deepEqual(await scalar('select * from ad_settlement_state where ad_id=1'),beforeState);
  assert.deepEqual(await scalar('select * from support_settlements where id=$1',[settlementId]),beforeSettlement);
});

test('expired transfer cannot POST again; completion can reconcile it without paying again', async () => {
  await db.query("update wallet_transfer_guards set first_attempt_at=now()-interval '21 hours' where settlement_id=$1",[settlementId]);
  const held = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(held.allowed,false);
  assert.equal(held.reason,'manual_review');
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',
    [settlementId,`adbattle-settlement-${settlementId}`,'req_verified','insufficient_capabilities_for_transfer']),/RECOVERY_BLOCKED/);
  const balanceArgs=[settlementId,`adbattle-settlement-${settlementId}-capability-recovery-1`,
    'req_balanceRejected','balance_insufficient',1912,'req_balanceSnapshot'];
  await assert.rejects(db.query('select authorize_wallet_balance_recovery($1,$2,$3,$4,$5,$6)',balanceArgs),/RECOVERY_BLOCKED/);
  await db.query('select complete_wallet_settlement($1,$2)',[settlementId,'tr_verified']);
  const duplicate = await scalar('select complete_wallet_settlement($1,$2) as completed',[settlementId,'tr_verified']);
  assert.equal(duplicate.completed,false);
  await assert.rejects(db.query('select authorize_wallet_balance_recovery($1,$2,$3,$4,$5,$6)',balanceArgs),/RECOVERY_REQUIRES/);
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',
    [settlementId,`adbattle-settlement-${settlementId}`,'req_verified','insufficient_capabilities_for_transfer']),/RECOVERY_REQUIRES/);
  assert.equal((await scalar('select pending_creator_micros from ad_settlement_state where ad_id=1')).pending_creator_micros,0);
});

test('actual 24-hour inactivity rule waits, resets on new Support, then settles', async () => {
  await db.query('insert into ads(id,user_id) values (2,$1)',[creator]);
  await db.query('select record_wallet_topup($1,$2,$3,5000)',['cs_creator','pi_creator',creator]);
  await db.query('select spend_wallet_support($1,2,1000,gen_random_uuid())',[creator]);
  const first=(await db.query('select * from claim_due_wallet_settlements(25)')).rows[0];
  await db.query('select complete_wallet_settlement($1,$2)',[first.settlement_id,'tr_ad2_first']);
  await db.query('select spend_wallet_support($1,2,1000,gen_random_uuid())',[creator]);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  await db.exec("update ad_settlement_state set last_support_at=now()-interval '25 hours' where ad_id=2");
  await db.query('select spend_wallet_support($1,2,1,gen_random_uuid())',[creator]);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  await db.exec("update ad_settlement_state set last_support_at=now()-interval '25 hours' where ad_id=2");
  const due=(await db.query('select * from claim_due_wallet_settlements(25)')).rows;
  assert.equal(due.length,1);
  assert.equal(due[0].trigger_reason,'inactivity');
  inFlightSettlementId=due[0].settlement_id;
});

test('recovery evidence cannot be partial, malformed or reused for another settlement', async () => {
  const key=`adbattle-settlement-${inFlightSettlementId}-capability-recovery-1`;
  const sql=`update wallet_transfer_guards set capability_recovery_key=$2,
    capability_recovery_request_id=$3, capability_recovered_at=$4 where settlement_id=$1`;
  const at=new Date().toISOString();
  for(const values of [
    [key,null,null], [null,'req_new',null], [null,null,at],
    [key,'req_new',null], [key,null,at], [null,'req_new',at],
    [key+'-another','req_new',at], [key,'invalid request',at],
  ]) await assert.rejects(db.query(sql,[inFlightSettlementId,...values]),/wallet_capability_recovery_complete/);
  await assert.rejects(db.query(sql,[inFlightSettlementId,key,'req_verified',at]),/unique constraint/);
  const guard=await scalar('select * from wallet_transfer_guards where settlement_id=$1',[inFlightSettlementId]);
  assert.equal(guard.capability_recovery_key,null);
  assert.equal(guard.capability_recovery_request_id,null);
  assert.equal(guard.capability_recovered_at,null);
});

test('balance recovery audit cannot be partial, malformed, lack its predecessor or reuse Stripe evidence',async()=>{
  const key=`adbattle-settlement-${inFlightSettlementId}-balance-recovery-1`;
  const at=new Date().toISOString();
  const update=`update wallet_transfer_guards set balance_recovery_key=$2,
    balance_recovery_request_id=$3,balance_recovery_balance_request_id=$4,
    balance_recovery_available_cents=$5,balance_recovered_at=$6 where settlement_id=$1`;
  const valid=[key,'req_newReject','req_newBalance',1912,at];
  // A full audit without a prior capability recovery must also be rejected.
  await assert.rejects(db.query(update,[inFlightSettlementId,...valid]),/wallet_balance_recovery_complete/);
  await db.query(`update wallet_transfer_guards set capability_recovery_key=$2,
    capability_recovery_request_id='req_previous',capability_recovered_at=now() where settlement_id=$1`,
    [inFlightSettlementId,`adbattle-settlement-${inFlightSettlementId}-capability-recovery-1`]);
  for(let i=0;i<valid.length;i++) {
    const partial=[...valid]; partial[i]=null;
    await assert.rejects(db.query(update,[inFlightSettlementId,...partial]),/wallet_balance_recovery_complete/);
  }
  for(const patch of [{0:key+'-other'},{1:'bad'},{2:'bad'},{2:'req_newReject'},{3:0}]) {
    const bad=[...valid]; for(const [index,value] of Object.entries(patch)) bad[index]=value;
    await assert.rejects(db.query(update,[inFlightSettlementId,...bad]),/wallet_balance_recovery_complete/);
  }
  for(const patch of [{1:'req_balanceRejected'},{2:'req_balanceSnapshot'}]) {
    const duplicate=[...valid]; for(const [index,value] of Object.entries(patch)) duplicate[index]=value;
    await assert.rejects(db.query(update,[inFlightSettlementId,...duplicate]),/unique constraint/);
  }
  assert.equal((await scalar('select balance_recovery_key from wallet_transfer_guards where settlement_id=$1',
    [inFlightSettlementId])).balance_recovery_key,null);
});

test('refunds debit only the cumulative delta, ignoring duplicates and old snapshots', async () => {
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_refund','pi_refund',refundUser]);
  for (const [amount,event] of [[300,'evt_1'],[300,'evt_1'],[500,'evt_2'],[300,'evt_old']]) {
    await db.query('select record_wallet_payment_risk($1,$2,$3,false,$4,$5)',
      ['pi_refund',refundUser,amount,event,'charge.refunded']);
  }
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[refundUser]);
  assert.equal(wallet.available_cents,500);
  assert.equal(wallet.status,'frozen');
  assert.equal((await scalar("select count(*)::int as n from wallet_transactions where user_id=$1 and entry_type='refund'",[refundUser])).n,2);
  await assert.rejects(db.query('select spend_wallet_support($1,1,1,gen_random_uuid())',[refundUser]),/WALLET_FROZEN/);
});

test('refund/dispute arriving before credit is retained and no later top-up unfreezes it', async () => {
  await db.query('select record_wallet_payment_risk($1,$2,1000,true,$3,$4)',
    ['pi_early',other,'evt_early','charge.dispute.created']);
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_early','pi_early',other]);
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[other]);
  assert.equal(wallet.available_cents,0);
  assert.equal(wallet.status,'frozen');
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_more','pi_more',other]);
  assert.equal((await scalar('select status from wallets where user_id=$1',[other])).status,'frozen');
});

test('refund after spending leaves a negative frozen balance and stops settlements', async () => {
  await db.query('select record_wallet_payment_risk($1,$2,1000,false,$3,$4)',
    ['pi_1',supporter,'evt_spent_refund','charge.refunded']);
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[supporter]);
  assert.equal(wallet.available_cents,-1000);
  assert.equal(wallet.status,'frozen');
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  const prepared=(await scalar('select prepare_wallet_transfer($1) as guard',[inFlightSettlementId])).guard;
  assert.equal(prepared.allowed,false);
  assert.equal(prepared.reason,'payment_risk_hold');
  await db.query('select retry_wallet_settlement($1,$2)',[inFlightSettlementId,'capability failure']);
  await assert.rejects(db.query('select authorize_wallet_capability_recovery($1,$2,$3,$4)',
    [inFlightSettlementId,`adbattle-settlement-${inFlightSettlementId}`,'req_verified','insufficient_capabilities_for_transfer']),/RECOVERY_BLOCKED/);
});

test('RLS limits reads and browser roles cannot invoke privileged money RPCs', async () => {
  await db.exec(`set role authenticated; set request.jwt.claim.sub='${supporter}';`);
  try {
    const wallets = (await db.query('select user_id from wallets')).rows;
    assert.deepEqual(wallets.map(w=>w.user_id),[supporter]);
    await assert.rejects(db.query('update wallets set available_cents=999999'),/permission denied/);
    await assert.rejects(db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_bad','pi_bad',supporter]),/permission denied/);
    await assert.rejects(db.query('select * from claim_due_wallet_settlements(25)'),/permission denied/);
    await assert.rejects(db.query('select * from wallet_payment_risks'),/permission denied/);
  } finally { await db.exec('reset role'); }
});

test('preparation wrapper refuses absent or non-boolean authorization from its predecessor', async () => {
  // Replace only the predecessor inside a rolled-back transaction so the real
  // wrapper is exercised against malformed authorization without persisting it.
  await db.exec('begin');
  try {
    await db.exec(`create or replace function public.prepare_wallet_transfer_before_recovery(p_settlement_id uuid)
      returns jsonb language sql security definer set search_path = '' as $$
      select current_setting('test.guard_result')::jsonb $$;`);
    for(const result of [null,{}, {allowed:null}, {allowed:false,reason:'manual_review'},
      {allowed:'true'}, {allowed:1}]) {
      await db.query("select set_config('test.guard_result',$1,true)",[JSON.stringify(result)]);
      const guard=(await scalar('select prepare_wallet_transfer($1) as g',[settlementId])).g;
      assert.equal(guard.allowed,false);
      assert.equal(guard.idempotency_key,undefined);
      if(result?.reason) assert.equal(guard.reason,result.reason);
    }
  } finally { await db.exec('rollback'); }
});
