import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { before, after, test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const db = new PGlite();
const supporter = '00000000-0000-4000-8000-000000000001';
const creator = '00000000-0000-4000-8000-000000000002';
const other = '00000000-0000-4000-8000-000000000003';
const refundUser = '00000000-0000-4000-8000-000000000004';
const scalar = async (sql, args = []) => (await db.query(sql, args)).rows[0];
before(async () => {
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    grant usage on schema public, auth to authenticated, anon, service_role;
    create table public.ads(id bigint primary key, user_id uuid references auth.users,
      support_total numeric default 0, moderation_status text default 'approved',
      promotion_stopped_at timestamptz, promotion_allocation jsonb default '{}');
    create table public.supports(id bigint generated by default as identity primary key,
      user_id uuid, ad_id bigint references public.ads, amount numeric check(amount >= 0.50),
      stripe_session_id text unique, stripe_payment_intent_id text unique);
    create table public.creator_accounts(user_id uuid primary key,
      stripe_account_id text, onboarding_complete boolean, charges_enabled boolean, payouts_enabled boolean);
    insert into auth.users values ('${supporter}'),('${creator}'),('${other}'),('${refundUser}');
    insert into public.ads(id,user_id) values (1,'${creator}');
    insert into public.creator_accounts values ('${creator}','acct_original',true,true,true);
  `);
  for (const file of ['20260920_wallet_ledger.sql', '20260921_wallet_safety.sql']) {
    let sql = readFileSync(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8');
    // PGlite has builtin gen_random_uuid; it does not ship the pgcrypto extension.
    sql = sql.replace('create extension if not exists pgcrypto;', '');
    await db.exec(sql);
  }
});
after(() => db.close());

test('actual RPC credits once and one-cent Support preserves exact shares', async () => {
  await db.query('select record_wallet_topup($1,$2,$3,1000)', ['cs_1','pi_1',supporter]);
  await db.query('select record_wallet_topup($1,$2,$3,1000)', ['cs_1','pi_1',supporter]);
  const request = '10000000-0000-4000-8000-000000000001';
  await db.query('select spend_wallet_support($1,1,1,$2)', [supporter,request]);
  await db.query('select spend_wallet_support($1,1,1,$2)', [supporter,request]);
  assert.equal((await scalar('select available_cents from wallets where user_id=$1',[supporter])).available_cents,999);
  const row = await scalar('select creator_amount_micros,platform_amount_micros from supports');
  assert.equal(row.creator_amount_micros,9000);
  assert.equal(row.platform_amount_micros,1000);
  await assert.rejects(db.query('select spend_wallet_support($1,1,2,$2)',[supporter,request]), /REQUEST_ID_CONFLICT/);
  await assert.rejects(db.query('select spend_wallet_support($1,1,1000,gen_random_uuid())',[supporter]), /INSUFFICIENT/);
});

let settlementId;
let inFlightSettlementId;
test('actual settlement claim and guard preserve destination and retry deadline', async () => {
  await db.query('select spend_wallet_support($1,1,999,gen_random_uuid())',[supporter]);
  const claimed = (await db.query('select * from claim_due_wallet_settlements(25)')).rows;
  assert.equal(claimed.length,1);
  assert.equal(claimed[0].creator_transfer_cents,900);
  settlementId = claimed[0].settlement_id;
  const first = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(first.allowed,true);
  await db.exec("update creator_accounts set stripe_account_id='acct_changed'");
  const second = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(second.destination,'acct_original');
  assert.equal(second.retry_before,first.retry_before);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
});

test('expired transfer cannot POST again; completion can reconcile it without paying again', async () => {
  await db.query("update wallet_transfer_guards set first_attempt_at=now()-interval '21 hours' where settlement_id=$1",[settlementId]);
  const held = (await scalar('select prepare_wallet_transfer($1) as guard',[settlementId])).guard;
  assert.equal(held.allowed,false);
  assert.equal(held.reason,'manual_review');
  await db.query('select complete_wallet_settlement($1,$2)',[settlementId,'tr_verified']);
  const duplicate = await scalar('select complete_wallet_settlement($1,$2) as completed',[settlementId,'tr_verified']);
  assert.equal(duplicate.completed,false);
  assert.equal((await scalar('select pending_creator_micros from ad_settlement_state where ad_id=1')).pending_creator_micros,0);
});

test('actual 24-hour inactivity rule waits, resets on new Support, then settles', async () => {
  await db.query('insert into ads(id,user_id) values (2,$1)',[creator]);
  await db.query('select record_wallet_topup($1,$2,$3,5000)',['cs_creator','pi_creator',creator]);
  await db.query('select spend_wallet_support($1,2,1000,gen_random_uuid())',[creator]);
  const first=(await db.query('select * from claim_due_wallet_settlements(25)')).rows[0];
  await db.query('select complete_wallet_settlement($1,$2)',[first.settlement_id,'tr_ad2_first']);
  await db.query('select spend_wallet_support($1,2,1000,gen_random_uuid())',[creator]);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  await db.exec("update ad_settlement_state set last_support_at=now()-interval '25 hours' where ad_id=2");
  await db.query('select spend_wallet_support($1,2,1,gen_random_uuid())',[creator]);
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  await db.exec("update ad_settlement_state set last_support_at=now()-interval '25 hours' where ad_id=2");
  const due=(await db.query('select * from claim_due_wallet_settlements(25)')).rows;
  assert.equal(due.length,1);
  assert.equal(due[0].trigger_reason,'inactivity');
  inFlightSettlementId=due[0].settlement_id;
});

test('refunds debit only the cumulative delta, ignoring duplicates and old snapshots', async () => {
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_refund','pi_refund',refundUser]);
  for (const [amount,event] of [[300,'evt_1'],[300,'evt_1'],[500,'evt_2'],[300,'evt_old']]) {
    await db.query('select record_wallet_payment_risk($1,$2,$3,false,$4,$5)',
      ['pi_refund',refundUser,amount,event,'charge.refunded']);
  }
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[refundUser]);
  assert.equal(wallet.available_cents,500);
  assert.equal(wallet.status,'frozen');
  assert.equal((await scalar("select count(*)::int as n from wallet_transactions where user_id=$1 and entry_type='refund'",[refundUser])).n,2);
  await assert.rejects(db.query('select spend_wallet_support($1,1,1,gen_random_uuid())',[refundUser]),/WALLET_FROZEN/);
});

test('refund/dispute arriving before credit is retained and no later top-up unfreezes it', async () => {
  await db.query('select record_wallet_payment_risk($1,$2,1000,true,$3,$4)',
    ['pi_early',other,'evt_early','charge.dispute.created']);
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_early','pi_early',other]);
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[other]);
  assert.equal(wallet.available_cents,0);
  assert.equal(wallet.status,'frozen');
  await db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_more','pi_more',other]);
  assert.equal((await scalar('select status from wallets where user_id=$1',[other])).status,'frozen');
});

test('refund after spending leaves a negative frozen balance and stops settlements', async () => {
  await db.query('select record_wallet_payment_risk($1,$2,1000,false,$3,$4)',
    ['pi_1',supporter,'evt_spent_refund','charge.refunded']);
  const wallet = await scalar('select available_cents,status from wallets where user_id=$1',[supporter]);
  assert.equal(wallet.available_cents,-1000);
  assert.equal(wallet.status,'frozen');
  assert.equal((await db.query('select * from claim_due_wallet_settlements(25)')).rows.length,0);
  const prepared=(await scalar('select prepare_wallet_transfer($1) as guard',[inFlightSettlementId])).guard;
  assert.equal(prepared.allowed,false);
  assert.equal(prepared.reason,'payment_risk_hold');
});

test('RLS limits reads and browser roles cannot invoke privileged money RPCs', async () => {
  await db.exec(`set role authenticated; set request.jwt.claim.sub='${supporter}';`);
  try {
    const wallets = (await db.query('select user_id from wallets')).rows;
    assert.deepEqual(wallets.map(w=>w.user_id),[supporter]);
    await assert.rejects(db.query('update wallets set available_cents=999999'),/permission denied/);
    await assert.rejects(db.query('select record_wallet_topup($1,$2,$3,1000)',['cs_bad','pi_bad',supporter]),/permission denied/);
    await assert.rejects(db.query('select * from claim_due_wallet_settlements(25)'),/permission denied/);
    await assert.rejects(db.query('select * from wallet_payment_risks'),/permission denied/);
  } finally { await db.exec('reset role'); }
});
