-- ============================================================
-- AdBattle detailed moderation v2
-- ============================================================
--
-- Adds:
--   - manual_review moderation status
--   - moderation audit fields on ads
--   - append-only moderation_events table
--   - exact image SHA-256 storage for duplicate/audit checks
--
-- Existing immutable-ad rules remain unchanged.
-- ============================================================

alter table public.ads
add column if not exists moderation_details jsonb;

alter table public.ads
add column if not exists moderation_risk_score integer;

alter table public.ads
add column if not exists moderation_scan_version text;

alter table public.ads
add column if not exists moderation_image_sha256 text;

alter table public.ads
add column if not exists moderation_last_error text;

alter table public.ads
add column if not exists moderation_attempts integer
not null default 0;

alter table public.ads
add column if not exists moderation_last_attempt_at timestamptz;


-- Expand the allowed status list to include manual_review.
alter table public.ads
drop constraint if exists ads_moderation_status_valid;

alter table public.ads
add constraint ads_moderation_status_valid
check (
  moderation_status in (
    'pending_scan',
    'manual_review',
    'approved',
    'rejected',
    'removed'
  )
);


-- Append-only internal scanner audit log.
create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete restrict,
  stage text not null,
  outcome text not null,
  reason text,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.moderation_events
enable row level security;

-- No browser policies are intentionally created.
-- service_role can still read/write this table.
revoke all
on public.moderation_events
from anon, authenticated;


-- Users cannot change scanner-controlled fields.
revoke update (
  moderation_status,
  moderation_reason,
  moderation_details,
  moderation_risk_score,
  moderation_scan_version,
  moderation_image_sha256,
  moderation_last_error,
  moderation_attempts,
  moderation_last_attempt_at,
  moderated_at,
  promotion_stopped_at
)
on public.ads
from anon, authenticated;


create index if not exists moderation_events_ad_id_idx
on public.moderation_events (ad_id, created_at desc);

create index if not exists ads_moderation_image_sha256_idx
on public.ads (moderation_image_sha256)
where moderation_image_sha256 is not null;