-- Minimal legacy schema, used only in the runner's disposable local cluster.
create role anon;
create role authenticated;
create role service_role;
create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as
  $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant usage on schema public, auth to authenticated, anon, service_role;
create table public.ads (
  id bigint primary key,
  user_id uuid references auth.users,
  support_total numeric default 0,
  moderation_status text default 'approved',
  promotion_stopped_at timestamptz,
  promotion_allocation jsonb default '{}'
);
create table public.supports (
  id bigint generated by default as identity primary key,
  user_id uuid,
  ad_id bigint references public.ads,
  amount numeric check (amount >= 0.50),
  stripe_session_id text unique,
  stripe_payment_intent_id text unique
);
create table public.creator_accounts (
  user_id uuid primary key,
  stripe_account_id text,
  onboarding_complete boolean,
  charges_enabled boolean,
  payouts_enabled boolean
);
