-- AdBattle wallet, 90/10 support ledger, and batched creator settlements.
--
-- Money rules implemented here:
--   * Supporters add at least $10 through Stripe Checkout.
--   * Wallet support can be any whole-cent amount, starting at $0.01.
--   * 90% accrues to the creator and 10% to AdBattle.
--   * Stripe charges the platform, so Stripe fees reduce AdBattle's share.
--   * Each ad settles at $10, $25, $50, $100, then doubling thresholds,
--     or after 24 hours without new support when at least $10 is pending.
--
-- Fractional creator/platform cents are stored as microdollars
-- (1 USD = 1,000,000 microdollars), so a $0.01 support splits exactly.

create extension if not exists pgcrypto;

-- ============================================================
-- WALLETS + TOP-UPS
-- ============================================================

create table if not exists public.wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  available_cents bigint not null default 0,
  lifetime_topup_cents bigint not null default 0 check (lifetime_topup_cents >= 0),
  lifetime_support_cents bigint not null default 0 check (lifetime_support_cents >= 0),
  status text not null default 'active' check (status in ('active', 'frozen')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_topups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  stripe_session_id text not null unique,
  stripe_payment_intent_id text unique,
  amount_cents bigint not null check (amount_cents between 1000 and 1000000),
  status text not null default 'paid' check (status in ('paid', 'partially_refunded', 'refunded', 'disputed')),
  reversed_cents bigint not null default 0 check (reversed_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (reversed_cents <= amount_cents)
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  entry_type text not null check (
    entry_type in ('topup', 'support_debit', 'refund', 'dispute', 'adjustment')
  ),
  amount_cents bigint not null check (amount_cents <> 0),
  balance_after_cents bigint not null,
  ad_id bigint references public.ads(id) on delete restrict,
  support_id bigint references public.supports(id) on delete restrict,
  topup_id bigint references public.wallet_topups(id) on delete restrict,
  request_id uuid,
  stripe_event_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists wallet_transactions_request_id_uidx
on public.wallet_transactions (request_id)
where request_id is not null;

create unique index if not exists wallet_transactions_stripe_event_id_uidx
on public.wallet_transactions (stripe_event_id)
where stripe_event_id is not null;

create index if not exists wallet_transactions_user_created_idx
on public.wallet_transactions (user_id, created_at desc);

-- ============================================================
-- SUPPORT SNAPSHOTS + SETTLEMENT STATE
-- ============================================================

alter table public.supports
add column if not exists source text not null default 'stripe_direct';

alter table public.supports
add column if not exists creator_share_percent numeric(5,2);

alter table public.supports
add column if not exists creator_amount numeric(18,6);

alter table public.supports
add column if not exists publishing_amount numeric(18,6);

alter table public.supports
add column if not exists platform_amount numeric(18,6);

alter table public.supports
add column if not exists promotion_allocation jsonb;

alter table public.supports
add column if not exists wallet_request_id uuid;

alter table public.supports
add column if not exists creator_amount_micros bigint;

alter table public.supports
add column if not exists platform_amount_micros bigint;

create unique index if not exists supports_wallet_request_id_uidx
on public.supports (wallet_request_id)
where wallet_request_id is not null;

do $$
declare
  constraint_row record;
begin
  -- Earlier AdBattle migrations required at least $0.50 per direct Stripe
  -- Support. Wallet Support starts at $0.01, so remove only amount checks
  -- that encode that old minimum before installing the new constraint.
  for constraint_row in
    select constraint_name.conname
    from pg_catalog.pg_constraint as constraint_name
    where constraint_name.conrelid = 'public.supports'::regclass
      and constraint_name.contype = 'c'
      and constraint_name.conkey @> array[
        (
          select attribute.attnum
          from pg_catalog.pg_attribute as attribute
          where attribute.attrelid = 'public.supports'::regclass
            and attribute.attname = 'amount'
        )
      ]::smallint[]
      and pg_catalog.pg_get_constraintdef(constraint_name.oid) ~* 'amount'
      and pg_catalog.pg_get_constraintdef(constraint_name.oid) ~* '(0[.]5|0[.]50|0[.]500)'
  loop
    execute format(
      'alter table public.supports drop constraint %I',
      constraint_row.conname
    );
  end loop;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.supports'::regclass
      and conname = 'supports_amount_at_least_one_cent'
  ) then
    alter table public.supports
      add constraint supports_amount_at_least_one_cent
      check (amount >= 0.01);
  end if;

  -- Wallet Support writes 90 explicitly. Keeping this column without a
  -- default prevents a legacy direct-Checkout completion during rollout
  -- from being mislabeled as a wallet-era 90/10 Support.
  alter table public.supports
    alter column creator_share_percent drop default;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'supports'
      and column_name = 'creator_amount'
  ) then
    alter table public.supports
      alter column creator_amount type numeric(18,6)
      using creator_amount::numeric(18,6);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'supports'
      and column_name = 'platform_amount'
  ) then
    alter table public.supports
      alter column platform_amount type numeric(18,6)
      using platform_amount::numeric(18,6);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'supports'
      and column_name = 'publishing_amount'
  ) then
    alter table public.supports
      alter column publishing_amount type numeric(18,6)
      using publishing_amount::numeric(18,6);
  end if;
end
$$;

create or replace function public.next_adbattle_threshold_cents(
  p_lifetime_cents bigint
)
returns bigint
language plpgsql
immutable
set search_path = ''
as $$
declare
  threshold_cents bigint;
begin
  if coalesce(p_lifetime_cents, 0) < 1000 then return 1000; end if;
  if p_lifetime_cents < 2500 then return 2500; end if;
  if p_lifetime_cents < 5000 then return 5000; end if;
  if p_lifetime_cents < 10000 then return 10000; end if;

  threshold_cents := 20000;
  while threshold_cents <= p_lifetime_cents loop
    threshold_cents := threshold_cents * 2;
  end loop;

  return threshold_cents;
end;
$$;

create table if not exists public.ad_settlement_state (
  ad_id bigint primary key references public.ads(id) on delete restrict,
  creator_user_id uuid not null references auth.users(id) on delete restrict,
  lifetime_support_cents bigint not null default 0 check (lifetime_support_cents >= 0),
  pending_creator_micros bigint not null default 0 check (pending_creator_micros >= 0),
  pending_platform_micros bigint not null default 0 check (pending_platform_micros >= 0),
  next_threshold_cents bigint not null default 1000 check (next_threshold_cents >= 1000),
  last_support_at timestamptz,
  last_settled_at timestamptz,
  active_settlement_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_settlements (
  id uuid primary key default gen_random_uuid(),
  ad_id bigint not null references public.ads(id) on delete restrict,
  creator_user_id uuid not null references auth.users(id) on delete restrict,
  trigger_reason text not null check (trigger_reason in ('threshold', 'inactivity')),
  gross_micros bigint not null check (gross_micros > 0),
  creator_micros bigint not null check (creator_micros > 0),
  platform_micros bigint not null check (platform_micros >= 0),
  creator_transfer_cents bigint not null check (creator_transfer_cents > 0),
  support_total_cents_snapshot bigint not null check (support_total_cents_snapshot >= 0),
  threshold_cents_snapshot bigint not null check (threshold_cents_snapshot >= 1000),
  stripe_transfer_id text unique,
  status text not null default 'processing' check (
    status in ('processing', 'retry', 'succeeded')
  ),
  attempts integer not null default 1 check (attempts > 0),
  next_attempt_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.ad_settlement_state'::regclass
      and conname = 'ad_settlement_state_active_settlement_fkey'
  ) then
    alter table public.ad_settlement_state
      add constraint ad_settlement_state_active_settlement_fkey
      foreign key (active_settlement_id)
      references public.support_settlements(id)
      on delete restrict;
  end if;
end
$$;

create index if not exists ad_settlement_state_due_idx
on public.ad_settlement_state (last_support_at)
where active_settlement_id is null;

create index if not exists support_settlements_retry_idx
on public.support_settlements (next_attempt_at)
where status = 'retry';

-- Treat previously recorded Support as already settled. This prevents a
-- migration from paying historical direct-Checkout support a second time.
insert into public.ad_settlement_state (
  ad_id,
  creator_user_id,
  lifetime_support_cents,
  next_threshold_cents,
  last_settled_at
)
select
  ads.id,
  ads.user_id,
  round(coalesce(ads.support_total, 0) * 100)::bigint,
  public.next_adbattle_threshold_cents(
    round(coalesce(ads.support_total, 0) * 100)::bigint
  ),
  now()
from public.ads
on conflict (ad_id) do nothing;

-- ============================================================
-- ATOMIC WALLET TOP-UP
-- ============================================================

create or replace function public.record_wallet_topup(
  p_stripe_session_id text,
  p_stripe_payment_intent_id text,
  p_user_id uuid,
  p_amount_cents bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_topup_id bigint;
  existing_topup public.wallet_topups%rowtype;
  new_balance bigint;
begin
  if p_amount_cents < 1000 then
    raise exception 'TOPUP_BELOW_MINIMUM';
  end if;

  if p_amount_cents > 1000000 then
    raise exception 'TOPUP_ABOVE_MAXIMUM';
  end if;

  insert into public.wallet_topups (
    user_id,
    stripe_session_id,
    stripe_payment_intent_id,
    amount_cents
  ) values (
    p_user_id,
    p_stripe_session_id,
    nullif(p_stripe_payment_intent_id, ''),
    p_amount_cents
  )
  on conflict do nothing
  returning id into inserted_topup_id;

  if inserted_topup_id is null then
    select * into existing_topup
    from public.wallet_topups
    where stripe_session_id = p_stripe_session_id
      or (
        nullif(p_stripe_payment_intent_id, '') is not null
        and stripe_payment_intent_id = nullif(p_stripe_payment_intent_id, '')
      )
    limit 1;

    if not found
      or existing_topup.user_id <> p_user_id
      or existing_topup.amount_cents <> p_amount_cents
    then
      raise exception 'TOPUP_IDEMPOTENCY_CONFLICT';
    end if;

    select available_cents into new_balance
    from public.wallets
    where user_id = p_user_id;

    return jsonb_build_object(
      'credited', false,
      'balance_cents', coalesce(new_balance, 0)
    );
  end if;

  insert into public.wallets (
    user_id,
    available_cents,
    lifetime_topup_cents
  ) values (
    p_user_id,
    p_amount_cents,
    p_amount_cents
  )
  on conflict (user_id) do update
  set
    available_cents = public.wallets.available_cents + excluded.available_cents,
    lifetime_topup_cents = public.wallets.lifetime_topup_cents + excluded.lifetime_topup_cents,
    status = public.wallets.status,
    updated_at = now()
  returning available_cents into new_balance;

  insert into public.wallet_transactions (
    user_id,
    entry_type,
    amount_cents,
    balance_after_cents,
    topup_id,
    metadata
  ) values (
    p_user_id,
    'topup',
    p_amount_cents,
    new_balance,
    inserted_topup_id,
    jsonb_build_object('stripe_session_id', p_stripe_session_id)
  );

  return jsonb_build_object(
    'credited', true,
    'balance_cents', new_balance
  );
end;
$$;

-- ============================================================
-- ATOMIC SUPPORT FROM WALLET
-- ============================================================

create or replace function public.spend_wallet_support(
  p_user_id uuid,
  p_ad_id bigint,
  p_amount_cents bigint,
  p_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  wallet_row public.wallets%rowtype;
  ad_row public.ads%rowtype;
  existing_transaction public.wallet_transactions%rowtype;
  support_id bigint;
  balance_after bigint;
  previous_support_cents bigint;
  new_support_total_cents bigint;
  gross_micros bigint;
  creator_micros bigint;
  platform_micros bigint;
begin
  if p_request_id is null then
    raise exception 'INVALID_REQUEST_ID';
  end if;

  if p_amount_cents < 1 then
    raise exception 'SUPPORT_BELOW_MINIMUM';
  end if;

  select * into existing_transaction
  from public.wallet_transactions
  where request_id = p_request_id;

  if found then
    if existing_transaction.user_id <> p_user_id
      or existing_transaction.entry_type <> 'support_debit'
      or existing_transaction.ad_id is distinct from p_ad_id
      or existing_transaction.amount_cents <> -p_amount_cents
    then
      raise exception 'REQUEST_ID_CONFLICT';
    end if;

    return jsonb_build_object(
      'recorded', false,
      'balance_cents', existing_transaction.balance_after_cents,
      'support_id', existing_transaction.support_id
    );
  end if;

  select * into wallet_row
  from public.wallets
  where user_id = p_user_id
  for update;

  if not found then
    raise exception 'WALLET_NOT_FUNDED';
  end if;

  -- A concurrent retry can only pass the first idempotency check before this
  -- wallet row is locked. Check again after serialization.
  select * into existing_transaction
  from public.wallet_transactions
  where request_id = p_request_id;

  if found then
    if existing_transaction.user_id <> p_user_id
      or existing_transaction.entry_type <> 'support_debit'
      or existing_transaction.ad_id is distinct from p_ad_id
      or existing_transaction.amount_cents <> -p_amount_cents
    then
      raise exception 'REQUEST_ID_CONFLICT';
    end if;

    return jsonb_build_object(
      'recorded', false,
      'balance_cents', existing_transaction.balance_after_cents,
      'support_id', existing_transaction.support_id
    );
  end if;

  if wallet_row.status <> 'active' then
    raise exception 'WALLET_FROZEN';
  end if;

  if wallet_row.available_cents < p_amount_cents then
    raise exception 'INSUFFICIENT_WALLET_BALANCE';
  end if;

  select * into ad_row
  from public.ads
  where id = p_ad_id
  for update;

  if not found then
    raise exception 'AD_NOT_FOUND';
  end if;

  if ad_row.moderation_status <> 'approved' or ad_row.promotion_stopped_at is not null then
    raise exception 'AD_NOT_APPROVED';
  end if;

  previous_support_cents := round(coalesce(ad_row.support_total, 0) * 100)::bigint;
  new_support_total_cents := previous_support_cents + p_amount_cents;
  gross_micros := p_amount_cents * 10000;
  creator_micros := gross_micros * 90 / 100;
  platform_micros := gross_micros - creator_micros;

  insert into public.supports (
    user_id,
    ad_id,
    amount,
    stripe_session_id,
    stripe_payment_intent_id,
    creator_share_percent,
    creator_amount,
    publishing_amount,
    platform_amount,
    source,
    wallet_request_id,
    creator_amount_micros,
    platform_amount_micros,
    promotion_allocation
  ) values (
    p_user_id,
    p_ad_id,
    p_amount_cents::numeric / 100,
    'wallet:' || p_request_id::text,
    'wallet:' || p_request_id::text,
    90,
    creator_micros::numeric / 1000000,
    0,
    platform_micros::numeric / 1000000,
    'wallet',
    p_request_id,
    creator_micros,
    platform_micros,
    coalesce(ad_row.promotion_allocation, '{}'::jsonb)
  )
  returning id into support_id;

  update public.wallets
  set
    available_cents = available_cents - p_amount_cents,
    lifetime_support_cents = lifetime_support_cents + p_amount_cents,
    updated_at = now()
  where user_id = p_user_id
  returning available_cents into balance_after;

  update public.ads
  set support_total = new_support_total_cents::numeric / 100
  where id = p_ad_id;

  insert into public.ad_settlement_state (
    ad_id,
    creator_user_id,
    lifetime_support_cents,
    pending_creator_micros,
    pending_platform_micros,
    next_threshold_cents,
    last_support_at
  ) values (
    p_ad_id,
    ad_row.user_id,
    new_support_total_cents,
    creator_micros,
    platform_micros,
    public.next_adbattle_threshold_cents(previous_support_cents),
    now()
  )
  on conflict (ad_id) do update
  set
    creator_user_id = excluded.creator_user_id,
    lifetime_support_cents = excluded.lifetime_support_cents,
    pending_creator_micros = public.ad_settlement_state.pending_creator_micros + creator_micros,
    pending_platform_micros = public.ad_settlement_state.pending_platform_micros + platform_micros,
    last_support_at = now(),
    updated_at = now();

  insert into public.wallet_transactions (
    user_id,
    entry_type,
    amount_cents,
    balance_after_cents,
    ad_id,
    support_id,
    request_id,
    metadata
  ) values (
    p_user_id,
    'support_debit',
    -p_amount_cents,
    balance_after,
    p_ad_id,
    support_id,
    p_request_id,
    jsonb_build_object(
      'creator_micros', creator_micros,
      'platform_micros', platform_micros
    )
  );

  return jsonb_build_object(
    'recorded', true,
    'balance_cents', balance_after,
    'support_id', support_id,
    'support_total_cents', new_support_total_cents,
    'creator_micros', creator_micros,
    'platform_micros', platform_micros
  );
end;
$$;

-- ============================================================
-- SETTLEMENT CLAIM / RETRY / COMPLETION
-- ============================================================

create or replace function public.claim_due_wallet_settlements(
  p_limit integer default 25
)
returns table (
  settlement_id uuid,
  ad_id bigint,
  creator_user_id uuid,
  stripe_account_id text,
  creator_transfer_cents bigint,
  creator_micros bigint,
  platform_micros bigint,
  trigger_reason text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate record;
  new_settlement_id uuid;
  returned_count integer := 0;
begin
  -- Retry the same settlement ID so Stripe's idempotency key remains stable.
  for candidate in
    select
      settlements.id,
      settlements.ad_id,
      settlements.creator_user_id,
      settlements.creator_transfer_cents,
      settlements.creator_micros,
      settlements.platform_micros,
      settlements.trigger_reason,
      accounts.stripe_account_id
    from public.support_settlements as settlements
    join public.ad_settlement_state as state
      on state.active_settlement_id = settlements.id
    join public.creator_accounts as accounts
      on accounts.user_id = settlements.creator_user_id
    where (
        (
          settlements.status = 'retry'
          and settlements.next_attempt_at <= now()
        ) or (
          settlements.status = 'processing'
          and settlements.updated_at <= now() - interval '15 minutes'
        )
      )
      and accounts.stripe_account_id is not null
      and accounts.onboarding_complete = true
      and accounts.charges_enabled = true
      and accounts.payouts_enabled = true
    order by settlements.next_attempt_at
    limit greatest(1, least(coalesce(p_limit, 25), 100))
    for update of settlements skip locked
  loop
    update public.support_settlements
    set
      status = 'processing',
      attempts = attempts + 1,
      updated_at = now()
    where id = candidate.id;

    settlement_id := candidate.id;
    ad_id := candidate.ad_id;
    creator_user_id := candidate.creator_user_id;
    stripe_account_id := candidate.stripe_account_id;
    creator_transfer_cents := candidate.creator_transfer_cents;
    creator_micros := candidate.creator_micros;
    platform_micros := candidate.platform_micros;
    trigger_reason := candidate.trigger_reason;
    returned_count := returned_count + 1;
    return next;
  end loop;

  if returned_count >= greatest(1, least(coalesce(p_limit, 25), 100)) then
    return;
  end if;

  for candidate in
    select
      state.*,
      accounts.stripe_account_id,
      case
        when state.lifetime_support_cents >= state.next_threshold_cents then 'threshold'
        else 'inactivity'
      end as reason
    from public.ad_settlement_state as state
    join public.creator_accounts as accounts
      on accounts.user_id = state.creator_user_id
    where state.active_settlement_id is null
      and state.pending_creator_micros >= 10000
      and (
        state.lifetime_support_cents >= state.next_threshold_cents
        or (
          state.pending_creator_micros + state.pending_platform_micros >= 10000000
          and state.last_support_at <= now() - interval '24 hours'
        )
      )
      and accounts.stripe_account_id is not null
      and accounts.onboarding_complete = true
      and accounts.charges_enabled = true
      and accounts.payouts_enabled = true
    order by state.last_support_at
    limit greatest(0, greatest(1, least(coalesce(p_limit, 25), 100)) - returned_count)
    for update of state skip locked
  loop
    new_settlement_id := gen_random_uuid();

    insert into public.support_settlements (
      id,
      ad_id,
      creator_user_id,
      trigger_reason,
      gross_micros,
      creator_micros,
      platform_micros,
      creator_transfer_cents,
      support_total_cents_snapshot,
      threshold_cents_snapshot
    ) values (
      new_settlement_id,
      candidate.ad_id,
      candidate.creator_user_id,
      candidate.reason,
      candidate.pending_creator_micros + candidate.pending_platform_micros,
      candidate.pending_creator_micros,
      candidate.pending_platform_micros,
      floor(candidate.pending_creator_micros::numeric / 10000)::bigint,
      candidate.lifetime_support_cents,
      candidate.next_threshold_cents
    );

    update public.ad_settlement_state
    set
      active_settlement_id = new_settlement_id,
      updated_at = now()
    where ad_settlement_state.ad_id = candidate.ad_id;

    settlement_id := new_settlement_id;
    ad_id := candidate.ad_id;
    creator_user_id := candidate.creator_user_id;
    stripe_account_id := candidate.stripe_account_id;
    creator_transfer_cents := floor(candidate.pending_creator_micros::numeric / 10000)::bigint;
    creator_micros := candidate.pending_creator_micros;
    platform_micros := candidate.pending_platform_micros;
    trigger_reason := candidate.reason;
    return next;
  end loop;
end;
$$;

create or replace function public.retry_wallet_settlement(
  p_settlement_id uuid,
  p_error text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.support_settlements
  set
    status = 'retry',
    next_attempt_at = now() + interval '5 minutes',
    last_error = left(coalesce(p_error, 'Unknown transfer error'), 1000),
    updated_at = now()
  where id = p_settlement_id
    and status <> 'succeeded';
end;
$$;

create or replace function public.complete_wallet_settlement(
  p_settlement_id uuid,
  p_stripe_transfer_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  settlement_row public.support_settlements%rowtype;
  state_row public.ad_settlement_state%rowtype;
  transferred_creator_micros bigint;
begin
  select * into settlement_row
  from public.support_settlements
  where id = p_settlement_id
  for update;

  if not found then
    raise exception 'SETTLEMENT_NOT_FOUND';
  end if;

  if settlement_row.status = 'succeeded' then
    return false;
  end if;

  select * into state_row
  from public.ad_settlement_state
  where ad_id = settlement_row.ad_id
  for update;

  if state_row.active_settlement_id is distinct from settlement_row.id then
    raise exception 'SETTLEMENT_STATE_MISMATCH';
  end if;

  transferred_creator_micros := settlement_row.creator_transfer_cents * 10000;

  if state_row.pending_creator_micros < transferred_creator_micros
    or state_row.pending_platform_micros < settlement_row.platform_micros
  then
    raise exception 'SETTLEMENT_BALANCE_MISMATCH';
  end if;

  update public.ad_settlement_state
  set
    pending_creator_micros = pending_creator_micros - transferred_creator_micros,
    pending_platform_micros = pending_platform_micros - settlement_row.platform_micros,
    next_threshold_cents = public.next_adbattle_threshold_cents(
      settlement_row.support_total_cents_snapshot
    ),
    last_settled_at = now(),
    active_settlement_id = null,
    updated_at = now()
  where ad_id = settlement_row.ad_id;

  update public.support_settlements
  set
    stripe_transfer_id = p_stripe_transfer_id,
    status = 'succeeded',
    next_attempt_at = null,
    last_error = null,
    completed_at = now(),
    updated_at = now()
  where id = p_settlement_id;

  return true;
end;
$$;

-- ============================================================
-- RLS + FUNCTION PRIVILEGES
-- ============================================================

alter table public.wallets enable row level security;
alter table public.wallet_topups enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.ad_settlement_state enable row level security;
alter table public.support_settlements enable row level security;

drop policy if exists "Users can view their wallet" on public.wallets;
create policy "Users can view their wallet"
on public.wallets for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view their topups" on public.wallet_topups;
create policy "Users can view their topups"
on public.wallet_topups for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view their wallet transactions" on public.wallet_transactions;
create policy "Users can view their wallet transactions"
on public.wallet_transactions for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Creators can view their settlement state" on public.ad_settlement_state;
create policy "Creators can view their settlement state"
on public.ad_settlement_state for select to authenticated
using (auth.uid() = creator_user_id);

drop policy if exists "Creators can view their settlements" on public.support_settlements;
create policy "Creators can view their settlements"
on public.support_settlements for select to authenticated
using (auth.uid() = creator_user_id);

revoke all on public.wallets from anon;
revoke all on public.wallet_topups from anon;
revoke all on public.wallet_transactions from anon;
revoke all on public.ad_settlement_state from anon;
revoke all on public.support_settlements from anon;

grant select on public.wallets to authenticated;
grant select on public.wallet_topups to authenticated;
grant select on public.wallet_transactions to authenticated;
grant select on public.ad_settlement_state to authenticated;
grant select on public.support_settlements to authenticated;

revoke insert, update, delete on public.wallets from anon, authenticated;
revoke insert, update, delete on public.wallet_topups from anon, authenticated;
revoke insert, update, delete on public.wallet_transactions from anon, authenticated;
revoke insert, update, delete on public.ad_settlement_state from anon, authenticated;
revoke insert, update, delete on public.support_settlements from anon, authenticated;
revoke insert, update, delete on public.supports from anon, authenticated;

revoke all on function public.record_wallet_topup(text, text, uuid, bigint)
from public, anon, authenticated;
grant execute on function public.record_wallet_topup(text, text, uuid, bigint)
to service_role;

revoke all on function public.spend_wallet_support(uuid, bigint, bigint, uuid)
from public, anon, authenticated;
grant execute on function public.spend_wallet_support(uuid, bigint, bigint, uuid)
to service_role;

revoke all on function public.claim_due_wallet_settlements(integer)
from public, anon, authenticated;
grant execute on function public.claim_due_wallet_settlements(integer)
to service_role;

revoke all on function public.retry_wallet_settlement(uuid, text)
from public, anon, authenticated;
grant execute on function public.retry_wallet_settlement(uuid, text)
to service_role;

revoke all on function public.complete_wallet_settlement(uuid, text)
from public, anon, authenticated;
grant execute on function public.complete_wallet_settlement(uuid, text)
to service_role;
