-- Duplicate-image screening and creator attribution. This migration only
-- prepares data structures/functions; it does not enable storage or deploy a scanner.
begin;

alter table public.ads
  add column if not exists image_storage_path text,
  add column if not exists moderation_details jsonb,
  add column if not exists moderation_risk_score integer,
  add column if not exists moderation_scan_version text,
  add column if not exists moderation_image_sha256 text,
  add column if not exists moderation_last_error text,
  add column if not exists moderation_attempts integer not null default 0,
  add column if not exists moderation_last_attempt_at timestamptz,
  add column if not exists safety_status text,
  add column if not exists duplicate_status text,
  add column if not exists duplicate_of_ad_id bigint references public.ads(id) on delete set null,
  add column if not exists image_index_required boolean;

update public.ads set
  safety_status = case when moderation_status = 'approved' then 'passed'
    when moderation_status in ('rejected','removed') then 'failed' else 'pending' end,
  duplicate_status = case when moderation_status = 'approved' then 'passed' else 'pending' end,
  image_index_required = true
where safety_status is null or duplicate_status is null or image_index_required is null;

alter table public.ads
  alter column safety_status set default 'pending',
  alter column safety_status set not null,
  alter column duplicate_status set default 'pending',
  alter column duplicate_status set not null,
  alter column image_index_required set default false,
  alter column image_index_required set not null,
  add constraint ads_safety_status_valid check (safety_status in ('pending','passed','held','failed')),
  add constraint ads_duplicate_status_valid check (duplicate_status in
    ('pending','passed','review_identical','review_similar','duplicate_same_creator','rejected'));

-- Append-only audit data restored from the deployed safety scanner v2 schema.
create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete restrict,
  stage text not null,
  outcome text not null,
  reason text,
  details jsonb,
  created_at timestamptz not null default now()
);
create index if not exists moderation_events_ad_id_idx
  on public.moderation_events(ad_id,created_at desc);
create index if not exists ads_moderation_image_sha256_idx
  on public.ads(moderation_image_sha256) where moderation_image_sha256 is not null;
alter table public.moderation_events enable row level security;
revoke all on public.moderation_events from public,anon,authenticated;
grant all on public.moderation_events to service_role;
revoke update (moderation_status,moderation_reason,moderation_details,
  moderation_risk_score,moderation_scan_version,moderation_image_sha256,
  moderation_last_error,moderation_attempts,moderation_last_attempt_at,
  moderated_at,promotion_stopped_at) on public.ads from anon,authenticated;

create table public.ad_image_fingerprints (
  ad_id bigint primary key references public.ads(id) on delete cascade,
  sha256 bytea not null check (octet_length(sha256) = 32),
  visual_hash bit(64) not null,
  visual_hash_version text not null,
  scanned_at timestamptz not null default now()
);
create index ad_image_fingerprints_sha256_idx on public.ad_image_fingerprints(sha256);
create index ads_duplicate_review_idx on public.ads(duplicate_status)
  where duplicate_status in ('review_identical','review_similar');

create table public.ad_scan_attempts (
  id bigint generated always as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  outcome text not null check (outcome in ('completed','failed','legacy_indexed')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.ad_duplicate_review_decisions (
  id bigint generated always as identity primary key,
  ad_id bigint not null unique references public.ads(id) on delete restrict,
  matched_ad_id bigint not null references public.ads(id) on delete restrict,
  previous_duplicate_status text not null check (
    previous_duplicate_status in ('review_identical','review_similar')
  ),
  decision text not null check (decision in ('clear','reject')),
  reviewer_identity text not null check (length(trim(reviewer_identity)) >= 3),
  reason text not null check (length(trim(reason)) >= 10),
  created_at timestamptz not null default now()
);

create table public.ad_image_index_state (
  singleton boolean primary key default true check (singleton),
  ready boolean not null default false,
  completed_at timestamptz,
  notes text
);
insert into public.ad_image_index_state(singleton,ready,notes)
  values(true,false,'Existing-image backfill has not been verified');

create table public.ad_image_index_exceptions (
  ad_id bigint primary key references public.ads(id) on delete cascade,
  reason text not null check (length(trim(reason)) >= 10),
  reviewed_by text not null check (length(trim(reviewed_by)) >= 3),
  reviewed_at timestamptz not null default now()
);

-- The supplied schema has no creator display-name field. Add a narrowly scoped,
-- owner-maintained profile rather than deriving a public name from email/auth data.
create table public.creator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  handle text not null check (handle ~ '^[A-Za-z0-9_]{1,30}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index creator_profiles_handle_lower_uidx on public.creator_profiles(lower(handle));

alter table public.ad_image_fingerprints enable row level security;
alter table public.ad_scan_attempts enable row level security;
alter table public.ad_duplicate_review_decisions enable row level security;
alter table public.ad_image_index_state enable row level security;
alter table public.ad_image_index_exceptions enable row level security;
alter table public.creator_profiles enable row level security;
revoke all on public.ad_image_fingerprints, public.ad_scan_attempts,
  public.ad_duplicate_review_decisions, public.ad_image_index_state,
  public.ad_image_index_exceptions from public, anon, authenticated;
grant all on public.ad_image_fingerprints, public.ad_scan_attempts,
  public.ad_duplicate_review_decisions, public.ad_image_index_state,
  public.ad_image_index_exceptions to service_role;
revoke all on public.creator_profiles from anon, authenticated;
grant select on public.creator_profiles to anon, authenticated;
grant insert, update on public.creator_profiles to authenticated;
grant all on public.creator_profiles to service_role;
create policy "Creator profiles are public" on public.creator_profiles for select using (true);
create policy "Creators insert their profile" on public.creator_profiles for insert to authenticated
  with check (auth.uid() = user_id);
create policy "Creators update their profile" on public.creator_profiles for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Browser clients must use fixed-column read functions rather than selecting
-- scanner and moderation internals directly from public.ads.
drop policy if exists "Anyone can view approved ads" on public.ads;
drop policy if exists "Users can view their own ads" on public.ads;
revoke select on public.ads from public,anon,authenticated;
drop policy if exists "Service role can read authoritative ads" on public.ads;
create policy "Service role can read authoritative ads"
  on public.ads for select to service_role using (true);

create or replace function public.get_public_ads()
returns table(
  id bigint,
  user_id uuid,
  title text,
  caption text,
  image_url text,
  support_total numeric,
  created_at timestamptz,
  moderation_status text
) language sql stable security definer set search_path = '' as $$
  select a.id,a.user_id,a.title,a.caption,a.image_url,a.support_total,
    a.created_at,a.moderation_status
  from public.ads a
  where a.moderation_status='approved'
  order by a.created_at desc,a.id desc
$$;

create or replace function public.get_my_ads()
returns table(
  id bigint,
  user_id uuid,
  title text,
  caption text,
  image_url text,
  support_total numeric,
  created_at timestamptz,
  moderation_status text,
  duplicate_status text,
  duplicate_of_ad_id bigint
) language sql stable security definer set search_path = '' as $$
  select a.id,a.user_id,a.title,a.caption,a.image_url,a.support_total,
    a.created_at,a.moderation_status,a.duplicate_status,a.duplicate_of_ad_id
  from public.ads a
  where a.user_id=auth.uid()
  order by a.created_at desc,a.id desc
$$;

revoke all on function public.get_public_ads(),public.get_my_ads()
  from public,anon,authenticated;
grant execute on function public.get_public_ads() to anon,authenticated;
grant execute on function public.get_my_ads() to authenticated;

create or replace function public.enforce_ad_screening_gate()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    new.safety_status := 'pending';
    new.duplicate_status := 'pending';
    new.duplicate_of_ad_id := null;
    new.moderation_status := 'pending_scan';
  elsif new.moderation_status = 'approved'
        and (new.safety_status <> 'passed' or new.duplicate_status <> 'passed') then
    raise exception 'REQUIRED_SCREENING_INCOMPLETE';
  end if;
  return new;
end;
$$;
create trigger enforce_ad_screening_gate
before insert or update on public.ads for each row execute function public.enforce_ad_screening_gate();

create or replace function public.refresh_ad_moderation_status(p_ad_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
begin
  update public.ads set
    moderation_status = case
      when moderation_status = 'removed' then 'removed'
      when safety_status = 'failed' or duplicate_status = 'rejected' then 'rejected'
      when safety_status = 'passed' and duplicate_status = 'passed' then 'approved'
      else 'pending_scan'
    end,
    moderated_at = case when safety_status = 'passed' and duplicate_status = 'passed'
      then now() else moderated_at end
  where id = p_ad_id;
end;
$$;

create or replace function public.record_ad_duplicate_scan(
  p_ad_id bigint, p_sha256_hex text, p_visual_hash_hex text, p_visual_hash_version text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  target public.ads%rowtype;
  exact_match record;
  visual_match record;
  result_status text;
  matched_id bigint;
  distance integer;
begin
  if p_sha256_hex !~ '^[0-9a-f]{64}$' or p_visual_hash_hex !~ '^[0-9a-f]{16}$'
     or p_visual_hash_version <> 'dhash-9x8-luma-v1' then
    raise exception 'INVALID_FINGERPRINT';
  end if;
  select * into target from public.ads where id = p_ad_id for update;
  if not found then raise exception 'AD_NOT_FOUND'; end if;
  if target.duplicate_status <> 'pending' then
    return jsonb_build_object('status', target.duplicate_status, 'matched_ad_id', target.duplicate_of_ad_id);
  end if;
  -- Serialize index decisions so simultaneous exact or visual matches cannot
  -- both observe an empty index and pass.
  perform pg_advisory_xact_lock(hashtextextended('ad-image-scan-v1', 0));

  select a.id, a.user_id into exact_match
    from public.ad_image_fingerprints f join public.ads a on a.id = f.ad_id
    where f.sha256 = decode(p_sha256_hex, 'hex') and a.id <> p_ad_id
    order by a.created_at, a.id limit 1;
  if found then
    matched_id := exact_match.id;
    result_status := case when exact_match.user_id = target.user_id
      then 'duplicate_same_creator' else 'review_identical' end;
    distance := 0;
  else
    select a.id, bit_count(f.visual_hash # (('x' || p_visual_hash_hex)::bit(64)))::integer as d
      into visual_match
      from public.ad_image_fingerprints f join public.ads a on a.id = f.ad_id
      where f.visual_hash_version = p_visual_hash_version and a.id <> p_ad_id
        and bit_count(f.visual_hash # (('x' || p_visual_hash_hex)::bit(64))) <= 8
      order by d, a.created_at, a.id limit 1;
    if found then
      result_status := 'review_similar'; matched_id := visual_match.id; distance := visual_match.d;
    else
      result_status := 'passed';
    end if;
  end if;

  insert into public.ad_image_fingerprints(ad_id,sha256,visual_hash,visual_hash_version)
    values (p_ad_id,decode(p_sha256_hex,'hex'),(('x'||p_visual_hash_hex)::bit(64)),p_visual_hash_version);
  update public.ads set duplicate_status=result_status, duplicate_of_ad_id=matched_id,
    moderation_details=coalesce(moderation_details,'{}'::jsonb) || jsonb_build_object(
      'duplicate_check',jsonb_build_object('status',result_status,'matched_ad_id',matched_id,
        'visual_distance',distance,'hash_version',p_visual_hash_version))
    where id=p_ad_id;
  insert into public.ad_scan_attempts(ad_id,outcome,details) values
    (p_ad_id,'completed',jsonb_build_object('status',result_status,'matched_ad_id',matched_id,'visual_distance',distance));
  perform public.refresh_ad_moderation_status(p_ad_id);
  return jsonb_build_object('status',result_status,'matched_ad_id',matched_id,'visual_distance',distance);
end;
$$;

create or replace function public.record_ad_duplicate_scan_failure(p_ad_id bigint,p_error text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  -- Deliberately does not change duplicate_status from pending.
  insert into public.ad_scan_attempts(ad_id,outcome,details)
    values(p_ad_id,'failed',jsonb_build_object('error',left(coalesce(p_error,'Unknown error'),500)));
  perform public.refresh_ad_moderation_status(p_ad_id);
end;
$$;

create or replace function public.resolve_ad_duplicate_review(
  p_ad_id bigint, p_decision text, p_reviewer_identity text, p_reason text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  target public.ads%rowtype;
  normalized_decision text := lower(trim(coalesce(p_decision,'')));
  resulting_status text;
begin
  select * into target from public.ads where id=p_ad_id for update;
  if not found then raise exception 'AD_NOT_FOUND'; end if;
  if exists(select 1 from public.ad_duplicate_review_decisions where ad_id=p_ad_id) then
    raise exception 'DUPLICATE_REVIEW_ALREADY_RESOLVED';
  end if;
  if target.moderation_status = 'removed' then raise exception 'REMOVED_AD_CANNOT_BE_REVIEWED'; end if;
  if target.duplicate_status not in ('review_identical','review_similar') then
    raise exception 'DUPLICATE_REVIEW_NOT_HELD';
  end if;
  if target.duplicate_of_ad_id is null then raise exception 'DUPLICATE_REVIEW_MATCH_REQUIRED'; end if;
  if normalized_decision not in ('clear','reject') then raise exception 'INVALID_DUPLICATE_REVIEW_DECISION'; end if;
  if length(trim(coalesce(p_reviewer_identity,''))) < 3
     or length(trim(coalesce(p_reason,''))) < 10 then
    raise exception 'DUPLICATE_REVIEW_DETAILS_REQUIRED';
  end if;

  resulting_status := case when normalized_decision='clear' then 'passed' else 'rejected' end;
  insert into public.ad_duplicate_review_decisions(
    ad_id,matched_ad_id,previous_duplicate_status,decision,reviewer_identity,reason
  ) values (
    p_ad_id,target.duplicate_of_ad_id,target.duplicate_status,normalized_decision,
    trim(p_reviewer_identity),trim(p_reason)
  );
  -- Preserve the matched ad, fingerprint, and original duplicate_check details.
  update public.ads set duplicate_status=resulting_status where id=p_ad_id;
  perform public.refresh_ad_moderation_status(p_ad_id);
  return jsonb_build_object(
    'status',resulting_status,'decision',normalized_decision,
    'matched_ad_id',target.duplicate_of_ad_id
  );
end;
$$;

create or replace function public.record_ad_legacy_fingerprint(
  p_ad_id bigint, p_sha256_hex text, p_visual_hash_hex text, p_visual_hash_version text
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare target public.ads%rowtype;
begin
  if p_sha256_hex !~ '^[0-9a-f]{64}$' or p_visual_hash_hex !~ '^[0-9a-f]{16}$'
     or p_visual_hash_version <> 'dhash-9x8-luma-v1' then raise exception 'INVALID_FINGERPRINT'; end if;
  perform pg_advisory_xact_lock(hashtextextended('ad-image-scan-v1',0));
  select * into target from public.ads where id=p_ad_id for update;
  if not found then raise exception 'AD_NOT_FOUND'; end if;
  if not target.image_index_required then raise exception 'NOT_A_LEGACY_AD'; end if;
  if exists(select 1 from public.ad_image_index_exceptions where ad_id=p_ad_id) then
    raise exception 'LEGACY_AD_HAS_REVIEWED_EXCEPTION';
  end if;
  insert into public.ad_image_fingerprints(ad_id,sha256,visual_hash,visual_hash_version)
    values(p_ad_id,decode(p_sha256_hex,'hex'),(('x'||p_visual_hash_hex)::bit(64)),p_visual_hash_version)
    on conflict(ad_id) do nothing;
  insert into public.ad_scan_attempts(ad_id,outcome,details) values
    (p_ad_id,'legacy_indexed',jsonb_build_object('publication_status_preserved',target.moderation_status));
  return jsonb_build_object('status','legacy_indexed','publication_status',target.moderation_status);
end;
$$;

create or replace function public.record_ad_legacy_scan_failure(p_ad_id bigint,p_error text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not exists(select 1 from public.ads where id=p_ad_id and image_index_required) then
    raise exception 'NOT_A_LEGACY_AD';
  end if;
  insert into public.ad_scan_attempts(ad_id,outcome,details) values
    (p_ad_id,'failed',jsonb_build_object('legacy_backfill',true,'error',left(coalesce(p_error,'Unknown error'),500)));
end;
$$;

create or replace function public.record_ad_image_index_exception(
  p_ad_id bigint,p_reason text,p_reviewed_by text
) returns void language plpgsql security definer set search_path = '' as $$
begin
  if exists(select 1 from public.ad_image_fingerprints where ad_id=p_ad_id) then
    raise exception 'LEGACY_AD_ALREADY_INDEXED';
  end if;
  if not exists(select 1 from public.ads where id=p_ad_id and image_index_required) then
    raise exception 'NOT_A_LEGACY_AD';
  end if;
  insert into public.ad_image_index_exceptions(ad_id,reason,reviewed_by)
    values(p_ad_id,trim(p_reason),trim(p_reviewed_by));
end;
$$;

create or replace function public.complete_ad_image_index_backfill(p_notes text,p_reviewed_by text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('ad-image-scan-v1',0));
  if length(trim(coalesce(p_notes,''))) < 10 or length(trim(coalesce(p_reviewed_by,''))) < 3 then
    raise exception 'BACKFILL_REVIEW_DETAILS_REQUIRED';
  end if;
  if exists(
    select 1 from public.ads a where a.image_index_required
      and not exists(select 1 from public.ad_image_fingerprints f where f.ad_id=a.id)
      and not exists(select 1 from public.ad_image_index_exceptions e where e.ad_id=a.id)
  ) then raise exception 'LEGACY_IMAGE_ACCOUNTING_INCOMPLETE'; end if;
  update public.ad_image_index_state set ready=true,completed_at=now(),
    notes=trim(p_notes)||' (reviewed by '||trim(p_reviewed_by)||')' where singleton;
end;
$$;

create or replace function public.record_ad_safety_scan(p_ad_id bigint,p_status text,p_reason text default null)
returns void language plpgsql security definer set search_path = '' as $$
declare target public.ads%rowtype;
begin
  if p_status not in ('passed','held','failed') then raise exception 'INVALID_SAFETY_STATUS'; end if;
  select * into target from public.ads where id=p_ad_id for update;
  if not found then raise exception 'AD_NOT_FOUND'; end if;
  if target.safety_status = p_status then return; end if;
  if target.safety_status <> 'pending' then raise exception 'SAFETY_STATUS_TERMINAL'; end if;
  update public.ads set safety_status=p_status, moderation_reason=p_reason where id=p_ad_id;
  perform public.refresh_ad_moderation_status(p_ad_id);
end;
$$;

revoke all on function public.refresh_ad_moderation_status(bigint),
  public.record_ad_duplicate_scan(bigint,text,text,text),
  public.record_ad_duplicate_scan_failure(bigint,text),
  public.resolve_ad_duplicate_review(bigint,text,text,text),
  public.record_ad_legacy_fingerprint(bigint,text,text,text),
  public.record_ad_legacy_scan_failure(bigint,text),
  public.record_ad_image_index_exception(bigint,text,text),
  public.complete_ad_image_index_backfill(text,text),
  public.record_ad_safety_scan(bigint,text,text) from public,anon,authenticated;
grant execute on function public.record_ad_duplicate_scan(bigint,text,text,text),
  public.record_ad_duplicate_scan_failure(bigint,text),
  public.resolve_ad_duplicate_review(bigint,text,text,text),
  public.record_ad_legacy_fingerprint(bigint,text,text,text),
  public.record_ad_legacy_scan_failure(bigint,text),
  public.record_ad_image_index_exception(bigint,text,text),
  public.complete_ad_image_index_backfill(text,text),
  public.record_ad_safety_scan(bigint,text,text) to service_role;

-- Legacy rows are marked image_index_required without changing publication.
-- The service-only backfill path must fingerprint or explicitly except each one.
commit;
