-- TEST PROJECT ONLY: adbattle-test (nccqnrcdygujulrnwair).
-- Confirm the project in the dashboard before running. This script cannot
-- verify the dashboard project ID. Never run it on the live project.
-- Recreates the supplied base schema, without data, secrets or scan-ad trigger.
-- RLS is explicitly enabled; grants are limited to the test app's needs.
-- Run once, then apply the two wallet migrations in date order.
begin;

do $$
begin
  if to_regclass('public.ads') is not null
     or to_regclass('public.supports') is not null
     or to_regclass('public.creator_accounts') is not null
     or to_regclass('public.wallets') is not null then
    raise exception 'Expected an empty test project. No changes made; do not drop existing tables.';
  end if;
end $$;

create table public.ads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  title text not null,
  caption text,
  image_url text not null,
  likes integer default 0,
  support_total numeric default 0,
  created_at timestamptz default now(),
  promotion_allocation jsonb not null default '{"tiktok":20,"youtube":20,"facebook":20,"snapchat":20,"instagram":20}'::jsonb,
  moderation_status text not null default 'pending_scan',
  moderation_reason text,
  moderated_at timestamptz,
  promotion_stopped_at timestamptz,
  moderation_details jsonb,
  constraint ads_moderation_status_valid check (
    moderation_status in ('pending_scan','approved','rejected','removed')
  ),
  constraint ads_promotion_allocation_valid check (
    jsonb_typeof(promotion_allocation) = 'object'
    and promotion_allocation ?& array['youtube','instagram','tiktok','snapchat','facebook']
    and (promotion_allocation->>'youtube')::numeric between 0 and 100
    and (promotion_allocation->>'instagram')::numeric between 0 and 100
    and (promotion_allocation->>'tiktok')::numeric between 0 and 100
    and (promotion_allocation->>'snapchat')::numeric between 0 and 100
    and (promotion_allocation->>'facebook')::numeric between 0 and 100
    and (promotion_allocation->>'youtube')::numeric
      + (promotion_allocation->>'instagram')::numeric
      + (promotion_allocation->>'tiktok')::numeric
      + (promotion_allocation->>'snapchat')::numeric
      + (promotion_allocation->>'facebook')::numeric = 100
  )
);
create index ads_moderation_status_idx on public.ads(moderation_status);

create table public.creator_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_account_id text unique,
  onboarding_complete boolean default false,
  charges_enabled boolean default false,
  payouts_enabled boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.supports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  ad_id bigint references public.ads(id) on delete cascade,
  amount numeric not null,
  created_at timestamptz default now(),
  stripe_session_id text,
  stripe_payment_intent_id text,
  creator_amount numeric,
  publishing_amount numeric,
  platform_amount numeric,
  promotion_allocation jsonb
);
create unique index supports_stripe_session_id_unique
  on public.supports(stripe_session_id);

alter table public.ads enable row level security;
alter table public.creator_accounts enable row level security;
alter table public.supports enable row level security;
create policy "Anyone can view approved ads" on public.ads
  for select to anon, authenticated using (moderation_status = 'approved');
create policy "Users can create their own ads" on public.ads
  for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can view their own ads" on public.ads
  for select to authenticated using (auth.uid() = user_id);
create policy "Users can view their own creator account" on public.creator_accounts
  for select to authenticated using (auth.uid() = user_id);
-- Preserves the supplied read policy. Use synthetic data only in this project.
create policy "Anyone can view supports" on public.supports
  for select to public using (true);

revoke all on public.ads, public.supports, public.creator_accounts from anon, authenticated;
grant select on public.ads, public.supports to anon, authenticated;
grant insert on public.ads to authenticated;
grant select on public.creator_accounts to authenticated;
grant usage on sequence public.ads_id_seq to authenticated;
grant all on public.ads, public.supports, public.creator_accounts to service_role;
grant usage, select on sequence public.ads_id_seq, public.supports_id_seq to service_role;

-- No scanner trigger: test ads remain pending_scan until manually approved
-- by a test administrator. This is not a full clone of the live application.
commit;
